### ISSUE TITLE
hey man im clueless can ya help me?

### ISSUE THREAD

**Issue by Supersonicx2003** [wvsharber/BeatMapSynthesizer#36]
hey man im clueless can ya help me? i have pretty much no expince in python or aconda because i usally work in c#

**Comment by wvsharber** [comment]
Hi, I'm happy to help! I wrote some pretty clear instructions on how to get it working at the bottom of the main readme for this repo. If there is something specific you need help with in those instructions, feel free to let me know.

**Comment by Supersonicx2003** [comment]
it all sounds like gibberish for me, is there any chance you could send a video of it being set up, it would honestly help so much for me, I tend to learn best that way honestly

**Comment by wvsharber** [comment]
I can try to do that next week, but this is a really easy set up with only a few steps that I'm sure you can figure out if you give it some time: 

1. Install Anaconda/Python on your system. (Anaconda includes Python, so this is one easy step)
2. Download this repo and activate the Python environment that is appropriate for your system.
3. Download and unzip the models that drive the program
4. Run the program from the command line

That's really it! I provide specific commands for each step in the readme, but I'm going to do some editing to the readme right now to hopefully make my instructions clearer.

**Comment by Supersonicx2003** [comment]
ok thank you

**Comment by Supersonicx2003** [comment]
sorry man, turns out I'm an idiot I did it in both python and regular command prompt not realising that I needed to do it in the anaconda one

**Comment by wvsharber** [comment]
Ah, yes that is a little tricky. I hope that fixed your problem. If not, I just restructured the installation instructions, so hopefully they're clearer now. Again, let me know if you encounter anymore issues.

**Comment by Supersonicx2003** [comment]
i think ive done something else wrong 
![image](https://user-images.githubusercontent.com/56960072/81446454-d1c6fe00-9172-11ea-8920-a47b5200bd13.png)

**Comment by wvsharber** [comment]
Ok, I think I see a couple potential issues here. 

1. You may need to wrap your song paths in double quotations or something since the file names have spaces.
2. The last error says that the package 'librosa' wasn't found in the Python environment (although it looks like it was installed by conda and the top of that page). Can you run this command and tell me if you see librosa listed? `conda list`

**Comment by Supersonicx2003** [comment]
i didnt do the song paths and that in doubtle qoutations because it looks like that was for mac and im on windows 10.

and here us what was outputed when i did "conda list"

# packages in environment at D:\python\Anaconda\envs\BSMapSynth-env:
#
# Name                    Version                   Build  Channel
audioread                 2.1.8                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py38_0
cffi                      1.14.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
ffmpeg                    4.2.2                he774522_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2020.0                      166
joblib                    0.14.1                   pypi_0    pypi
librosa                   0.7.2                    pypi_0    pypi
llvmlite                  0.32.0                   pypi_0    pypi
markovify                 0.8.0                    pypi_0    pypi
mkl                       2020.0                      166
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.0.15           py38h14836fe_0
mkl_random                1.1.0            py38hf9181ef_0
numba                     0.49.0                   pypi_0    pypi
numpy                     1.18.1           py38h93ca92e_0
numpy-base                1.18.1           py38hc3f5095_1
openssl                   1.1.1g               he774522_0
pandas                    1.0.3            py38h47e9c7a_0
pip                       20.0.2                   py38_3
pycparser                 2.20                     pypi_0    pypi
pydub                     0.23.1                   pypi_0    pypi
python                    3.8.2               he1778fa_13
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
resampy                   0.2.2                    pypi_0    pypi
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.1.3                   py38_0
six                       1.14.0                   py38_0
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.31.1               h2a8f88b_1
tbb                       2020.0               h74a9793_0
unidecode                 1.1.1                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                   py38_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4

(BSMapSynth-env) D:\mixer\to upload\BeatMapSynthesizer-master\BeatMapSynthesizer-master>

**Comment by wvsharber** [comment]
That's only for the case if there are no spaces in the file path you provide. Otherwise, you need to wrap the file path in double quotes, e.g., "C:\Desktop\to upload\"

I think that should fix your first problem. 

Looking back at the second problem, it looks like you didn't prepend the command to run beatmapsynth.py with python. I'm not sure if that will fix your problem, but try it again with:

`python beatmapsynth.py filepath ...`

**Comment by Supersonicx2003** [comment]
I've semi-fixed the Librosa issue by updating it, and iv managed to get to this point 


![image](https://user-images.githubusercontent.com/56960072/81449277-d04c0480-9177-11ea-84a6-e7c922c699ac.png)



(BSMapSynth-env) D:\mixer\to upload\BeatMapSynthesizer-master\BeatMapSynthesizer-master>python beatmapsynth.py "D:\music"  "Tsuko G. - Break Free (Official Music Video)" "normal" "rate_modulated_segmented_HMM" "-k 5" --version 1
Loading Song...
Traceback (most recent call last):
  File "beatmapsynth.py", line 719, in <module>
    beat_map_synthesizer(args.song_path, args.song_name, args.difficulty, args.model, args.k, args.version)
  File "beatmapsynth.py", line 50, in beat_map_synthesizer
    rate_modulated_segmented_HMM_mapper(song_path, song_name, difficulty, version = version, k = k)
  File "beatmapsynth.py", line 499, in rate_modulated_segmented_HMM_mapper
    bpm, beat_times, y, sr = beat_features(song_path)
  File "beatmapsynth.py", line 182, in beat_features
    y, sr = librosa.load(song_path)
  File "D:\python\Anaconda\envs\BSMapSynth-env\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "D:\python\Anaconda\envs\BSMapSynth-env\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\python\Anaconda\envs\BSMapSynth-env\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
PermissionError: [Errno 13] Permission denied: 'D:\\music'

(BSMapSynth-env) D:\mixer\to upload\BeatMapSynthesizer-master\BeatMapSynthesizer-master>

**Comment by wvsharber** [comment]
Ok, looks like you're getting close then, we just need to make sure your command line instructions are correct. Is your music file in the folder "D:\music\"? If so, your full command should probably look like this:

`python beatmapsynth.py "D:\music\Tsuko G. - Break Free (Official Music Video)" "Tsuko G. - Break Free (Official Music Video)" normal rate_modulated_segmented_HMM -k 5 --version 1`

**Comment by Supersonicx2003** [comment]
its 

python beatmapsynth.py "D:\music"  "Tsuko G. - Break Free (Official Music Video)" "normal" "rate_modulated_segmented_HMM" "-k 5" --version 1

it works well but i get "PermissionError: [Errno 13] Permission denied: 'D:\music""

**Comment by Supersonicx2003** [comment]
and i tried yours and got this 

(BSMapSynth-env) D:\mixer\to upload\BeatMapSynthesizer-master\BeatMapSynthesizer-master>python beatmapsynth.py "D:\music\Tsuko G. - Break Free (Official Music Video)" "Tsuko G. - Break Free (Official Music Video)" normal rate_modulated_segmented_HMM -k 5 --version 1
Loading Song...
Traceback (most recent call last):
  File "beatmapsynth.py", line 719, in <module>
    beat_map_synthesizer(args.song_path, args.song_name, args.difficulty, args.model, args.k, args.version)
  File "beatmapsynth.py", line 50, in beat_map_synthesizer
    rate_modulated_segmented_HMM_mapper(song_path, song_name, difficulty, version = version, k = k)
  File "beatmapsynth.py", line 499, in rate_modulated_segmented_HMM_mapper
    bpm, beat_times, y, sr = beat_features(song_path)
  File "beatmapsynth.py", line 182, in beat_features
    y, sr = librosa.load(song_path)
  File "D:\python\Anaconda\envs\BSMapSynth-env\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "D:\python\Anaconda\envs\BSMapSynth-env\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\python\Anaconda\envs\BSMapSynth-env\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\music\\Tsuko G. - Break Free (Official Music Video)'

(BSMapSynth-env) D:\mixer\to upload\BeatMapSynthesizer-master\BeatMapSynthesizer-master>

**Comment by wvsharber** [comment]
I don't understand where your file is specifically. Did you just name the file "music" and put it in your root folder? Maybe you can send a screenshot of the folder where your music is?

**Comment by Supersonicx2003** [comment]
ok give me a sec

**Comment by Supersonicx2003** [comment]
![image](https://user-images.githubusercontent.com/56960072/81450513-80227180-917a-11ea-999e-d78812379efb.png)

**Comment by wvsharber** [comment]
Ok, here's another suggestion: use a "drag and drop" approach to get Windows to automatically input the file path for you. So in your Anaconda Prompt, type `python beatmapsynth.py` then drag the music file to the command line. It should paste in the file path. Then complete the command with the rest of the options.

**Comment by Supersonicx2003** [comment]
ok

**Comment by Supersonicx2003** [comment]
sadly i got this 

(BSMapSynth-env) D:\mixer\to upload\BeatMapSynthesizer-master\BeatMapSynthesizer-master>python beatmapsynth.py"D:\music\Tsuko G. - Break Free (Official Music Video).mp3" "normal" "rate_modulated_segmented_HMM" "-k 5" --version 1
python: can't open file 'beatmapsynth.pyD:\music\Tsuko G. - Break Free (Official Music Video).mp3': [Errno 22] Invalid argument

**Comment by wvsharber** [comment]
You're missing a space between beatmapsynth.py and the file path. You'll also need to add an option for what you want the name of the output zip folder to be. Try to copy the structure of the command I provided you earlier

**Comment by Supersonicx2003** [comment]
![image](https://user-images.githubusercontent.com/56960072/81451625-d1cbfb80-917c-11ea-99f5-e64306e71428.png)

**Comment by wvsharber** [comment]
`python beatmapsynth.py "D:\music\Tsuko G. - Break Free (Official Music Video).mp3" "Tsuko G. - Break Free (Official Music Video)" normal rate_modulated_segmented_HMM -k 5 --version 1`

**Comment by Supersonicx2003** [comment]
i think we are almost there copy and pasted it in and got a simple but different and easier error

![image](https://user-images.githubusercontent.com/56960072/81451993-9ed63780-917d-11ea-8c76-ce397baf7f74.png)

**Comment by wvsharber** [comment]
Did you download and unzip the folder with the models as per the installation instructions?

**Comment by Supersonicx2003** [comment]
yep 
![image](https://user-images.githubusercontent.com/56960072/81452133-fc6a8400-917d-11ea-8afc-e25c973c21ae.png)

**Comment by wvsharber** [comment]
Ah, I see the problem. You need to move all of those files out of the folder called "HMM_models copy" and into the folder above it called "models"

**Comment by Supersonicx2003** [comment]
ah i just extracted the foldere in there my bad

**Comment by wvsharber** [comment]
It's ok. I figured it would be an issue. I tried to write the instructions to avoid that, but I guess I need to be more clear.

**Comment by Supersonicx2003** [comment]
no its my bad i tend to rush read these sorta things, thanks for helping me today, i going to try out the song now

**Comment by wvsharber** [comment]
No worries! You're actually helping me to make sure all of my instructions are very clear! Plus reinforcing the need for an easier to set up program!

Enjoy! Let me know how it worked for you! I generally suggest that people map the same song a few times and keep the one you like the best.

**Comment by Supersonicx2003** [comment]
yeah im gonna try it now wish me luck

**Comment by Supersonicx2003** [comment]
well it works great, the mapping is good the flow of the blocks is amazing, the only problem is the easyness of it but i guess i did put it on normal, ill link you the go i had

**Comment by Supersonicx2003** [comment]
https://www.twitch.tv/videos/615250305, I'm gonna go get some shut eye, thank you for the help again. , can i suggest contacting the beat saber modding community on discord about adding it into that, because with more people and a launcher i believe this could be next level honestly. thanks again

**Comment by wvsharber** [comment]
Thanks for recording it! I'm glad we got it working. 

Are you suggesting that it's too easy on normal? I generally play on expert/expert+, so it's hard for me to evaluate how easy the easy and normal levels are. I've been meaning to reach out to that community for several reasons, mostly so I can get more people testing the levels.

**Comment by Supersonicx2003** [comment]
genrally its just not enough blocks to be considered a challenge in all honestly

**Comment by Supersonicx2003** [comment]
also if i restart the acaonda stuff do i have to redo the whole thing or just parts of it

**Comment by wvsharber** [comment]
Thanks for the feedback!

And good question. You'll just need to navigate to the BeatMapSynth folder again and reactivate the BSMapSynth-env by running this command: `conda activate BSMapSynth-env`. From there you can use it just like you did earlier!

**Comment by Supersonicx2003** [comment]
ok thank you, i was trying to redo it all

**Comment by Supersonicx2003** [comment]
i tried to make the song on a diffrent difficulty but then tis came up 
![image](https://user-images.githubusercontent.com/56960072/81457435-04cabb00-918e-11ea-914f-e07b3d98541f.png)

**Comment by wvsharber** [comment]
You need to fix the command. It has to follow a very specific sequence:

`python beatmapsynth.py "path_to_song_file" "Name of Song" difficulty_level model -k 5 --version 1`

If you have anything extra, missing (except the last two arguments which are technically optional), or in the wrong order, it won't work. 

Think of it this way: you're starting the command by saying you want to run something in python. Python then needs to know what it's executing, which is the beatmapsynth.py file. The beatmapsynth.py script needs four pieces of information: the song file, what name you want the output to be, the difficulty level, and which model to use. So every time you want to run the program, you have to say "hey python, run that script called beatmapsynth.py with these arguments." 

I know it's not very user friendly and I'm sorry about that, but as long as you make sure to follow that template above every time you run it, it should work. If your command doesn't look like that then it will fail. If you find that your command is written correctly and it still isn't working, then please do let me know.

**Comment by Supersonicx2003** [comment]
Is there a way to make the levels harder, because it all seems really easy no matter the difficulty?

**Comment by wvsharber** [comment]
You can try a couple of different things:

1. You can choose a higher difficulty level, which sounds like you've already done.

2. You can try changing the rate probabilities in the code to make the rate modulated HMM more likely to produce songs with a higher number of blocks per beat. 

In the beatmapsynth.py file, you'll find a function called "choose_rate." It takes in your chosen difficulty level and the average amplitude (or "loudness") across three beats in the music and returns a number of blocks to place for each beat. Less loud beats have a higher probability of returning a smaller number of blocks per beat (e.g., 0-1), while more loud beats have a higher probability of returning more blocks per beat (e.g., 4-8). The probabilities are hard coded and depend on which difficulty level you choose. If you wanted to try to make things "harder" by increasing the number of blocks per beat, you can change the probabilities in this function so that they favor higher number of blocks per beat. 

I don't exactly suggest doing this though, because I spent a long time trying to get those numbers right and I feel like they're fairly realistic to human-made maps, albeit a little easy for someone who has a high skill level. I have found times on expert/expert+ where the program will create a sequence of blocks at a high placement rate (maybe 8 per beat), but the sequence isn't playable at that rate. I suspect the only time you see >8 blocks per beat in most human made maps is for "drumrolls," and those follow a very specific up-down-up-down pattern, i.e., a tight controlled motion that is easy to perform at high rates of speed. BeatMapSynth isn't trained to know what block sequences work at higher speeds, so sometimes it produces sequences that just don't work well. 

That being said, I never expected this program to be a replacement for well-made, human-constructed maps. It is a tool for people to be able to play their favorite music quickly, and potentially use it as the building blocks for manually creating a map. 

I hope that answers your question!

**Comment by Supersonicx2003** [comment]
ok, thank you, ill ave a look and see what happens tonight
