### ISSUE TITLE
GUI fork

### ISSUE THREAD

**Issue by theace0296** [wvsharber/BeatMapSynthesizer#38]
@wvsharber I turned your project into an Electron-based GUI app that's all-inclusive. Let me know what you think! 
https://github.com/theace0296/BeatMapSynthesizer/releases

**Comment by wvsharber** [comment]
Wow! Thanks for doing this! I'll have to check it out when I can get on a Windows machine! I'll let you know when I get a chance to look at it!

**Comment by theace0296** [comment]
@wvsharber I forgot to mention, I wanted to add you on Discord, but I need the numbers after your username to do so. If you just want to add me, my DIscord is TheAce0296 (removed numbers for privacy since you've added me) 😃
