### ISSUE TITLE
error in making the song

### ISSUE THREAD

**Issue by Domsmasher1** [wvsharber/BeatMapSynthesizer#46]
![image](https://user-images.githubusercontent.com/47263379/85382693-9184d900-b582-11ea-906b-fea7cc6a4eeb.png)
heres an image of what i got, all the errors i got before with the python modules i just installed manually and i use the command to start it and i got this. have i done something wrong with installation. if so can you help me or make a video outlining how to install this because i believe it would help

**Comment by theace0296** [comment]
Did you download the models and place them in the /models folder? If not you can find the zipped models [here](https://drive.google.com/open?id=1p7j0sENy0DzcMHd3iQ_LQw14j6OcKLsY).

**Comment by Domsmasher1** [comment]
where is the /models folder

**Comment by Domsmasher1** [comment]
fixed it i needed to move the models out of a folder and also convert the song to an ogg file
